pipeline {
    agent any

    environment {
        DOCKER_USER   = 'amralaa21'
        IMAGE_NAME    = 'kubernetes-app'
        REPO_NAME     = 'AmrAlaaArafa/Ivolve_Devops_Training.git'
        IMAGE_TAG     = "v${env.BUILD_NUMBER}"
        FULL_IMAGE    = "${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {

        stage(' Build Docker Image') {
            steps {
              dir("Docker/lab9") {
                    sh "docker build -t $FULL_IMAGE ."
                }
            }
        }

        stage(' Push Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId:'dockerhub',usernameVariable:'DOCKER_USER',passwordVariable:'DOCKER_PASS')]){

              sh"""
                    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
                    docker push  $FULL_IMAGE
              """
            }
        }

        stage('4. Delete Image Locally') {
            steps {
                sh "docker rmi $FULL_IMAGE || true"

            }
        }

        stage(' Edit deployment.yaml') {
            steps {
                 dir("Kubernetes/lab15-16") {
                    sh """
                        sed -i "s|image .*|image: $FULL_IMAGE|" nodejs-deployment.yml
                        cp nodjs-deployment.yml /main/Jenkins/lab25
                    """
                }
            }
        }

        stage(' Push Updated Manifests to GitHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    sh """
                        git config user.name "Jenkins"
                        git config user.email "jenkins@ci-cd.local"
                        git add  nodjs-deployment.yml
                        git commit -m "ci: update deployment image to ${IMAGE_TAG} [skip ci]" || echo "No changes to commit"
                        git push https://${GIT_USER}:${GIT_PASS}@github.com/${REPO_NAME}.git HEAD:main
                    """
                }
            }
        }
    }
}
}
