apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: ivolve
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://hub.docker.com/repositories/amralaa21": {
          "username": "amralaa21",
          "password": "amralaaarafa@gmail.com",
          "email": "amralaaarafa@gmail.com"
        }
      }
    }